import React, { useState, useEffect, Suspense, lazy } from 'react';
import { User, UserRole, Governorate, Language, AppTab, Post, ThemeName, MainContentTab, HomeViewMode } from './types';
import * as api from './services/apiService';
import Header from './components/Header';
import Sidebar from './components/Sidebar';
import BottomBar from './components/BottomBar';
import LoginModal from './components/LoginModal';
import ComposeModal from './components/ComposeModal';
import { colorThemes } from './utils/colorThemes';
import LanguageSwitcher from './components/LanguageSwitcher';
import PostDetailModal from './components/PostDetailModal';
import Countdown from './components/Countdown';
import Spinner from './components/Spinner';
import ViewModeSwitcher from './components/ViewModeSwitcher';
