export const IRAQ_GOVERNORATES = [
    { id: 1, name: 'بغداد', enName: 'Baghdad' },
    { id: 2, name: 'البصرة', enName: 'Basra' },
    { id: 3, name: 'نينوى', enName: 'Nineveh' },
    { id: 4, name: 'أربيل', enName: 'Erbil' },
    { id: 5, name: 'الأنبار', enName: 'Anbar' },
    { id: 6, name: 'ذي قار', enName: 'Dhi Qar' },
    { id: 7, name: 'صلاح الدين', enName: 'Salah al-Din' },
    { id: 8, name: 'ديالى', enName: 'Diyala' },
    { id: 9, name: 'كركوك', enName: 'Kirkuk' },
    { id: 10, name: 'السليمانية', enName: 'Sulaymaniyah' },
    { id: 11, name: 'بابل', enName: 'Babil' },
    { id: 12, name: 'واسط', enName: 'Wasit' },
    { id: 13, name: 'ميسان', enName: 'Maysan' },
    { id: 14, name: 'المثنى', enName: 'Muthanna' },
    { id: 15, name: 'القادسية', enName: 'Qadisiyyah' },
    { id: 16, name: 'النجف', enName: 'Najaf' },
    { id: 17, name: 'كربلاء', enName: 'Karbala' },
    { id: 18, name: 'دهوك', enName: 'Dohuk' },
];
