<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Smart Campaign</title>
    
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Noto+Sans+Arabic:wght@400;500;700&display=swap" rel="stylesheet">
    
    <!-- Tailwind CSS -->
    <script src="https://cdn.tailwindcss.com"></script>
    
    <!-- Beautiful Glass-morphism Styles -->
    <style>
        :root {
            --color-primary: #0D9488;
            --color-primary-rgb: 13, 148, 136;
            --color-primary-dark: #096B61;
            --color-primary-darker: #07524B;
            --color-primary-100: #CCFBF1;
            --color-secondary: #2DD4BF;
            --color-accent: #F000B8;
            --color-background: #100C1C;
            --color-background-soft: #1A1625;
            --color-background-image: radial-gradient(circle at 15% 50%, rgba(240, 0, 184, 0.6), transparent 35%),
                radial-gradient(circle at 85% 30%, rgba(45, 212, 191, 0.4), transparent 40%),
                radial-gradient(circle at 50% 90%, rgba(91, 33, 182, 0.5), transparent 45%);
            --color-glass-bg: rgba(26, 22, 37, 0.6);
            --color-glass-border: rgba(255, 255, 255, 0.1);
            --color-card-bg: rgba(26, 22, 37, 0.7);
            --color-card-text: #F1F5F9;
            --color-text-base: #F1F5F9;
            --color-text-muted: #CBD5E1;
            --color-text-deep: #F1F5F9;
            --color-text-on-primary: #FFFFFF;
            --color-primary-glow: rgba(13, 148, 136, 0.6);
            --color-border: rgba(255, 255, 255, 0.1);
            --color-border-dark: rgba(255, 255, 255, 0.15);
        }

        body {
            background-color: var(--color-background);
            background-image: var(--color-background-image);
            background-attachment: fixed;
            color: var(--color-text-base);
            transition: background-color 0.5s ease-in-out, color 0.5s ease-in-out;
        }

        .glass-card {
            background: var(--color-glass-bg);
            backdrop-filter: blur(30px);
            -webkit-backdrop-filter: blur(30px);
            border: 1px solid var(--color-glass-border);
            color: var(--color-card-text);
            text-shadow: 0 1
# Add the resolved index.html
git add index.html

# Commit everything on future-features branch
git commit -m "chore: add CI workflow, resolve conflicts, add new features"

# Push to future-features
git push origin future-features
# Add the resolved index.html
git add index.html

# Commit everything on future-features branch
git commit -m "chore: add CI workflow, resolve conflicts, add new features"

# Push to future-features
git push origin future-features
# Checkout setup-scaffold
git checkout setup-scaffold

# Verify CI file exists
ls .github/workflows/

# If ci.yml doesn't exist on this branch, create it:
@"
name: CI

on:
  pull_request:
    branches:
      - main
      - frontend
      - backend
      - data
      - ai-automation
      - marketing
      - future-features

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install
        run: |
          if [ -f package.json ]; then npm ci; fi
      - name: Lint
        run: |
          if npm run -s lint; then echo "lint ok"; fi
      - name: Build
        run: |
          if npm run -s build; then echo "build ok"; fi
